const iconsPath = "/assets/icons/";

const ICON = {
  GLOBAL: {
    LOGO: `${iconsPath}logo.svg`,
    LOGO_2: `${iconsPath}logo-icon.svg`,
    FAV_ICON: `${iconsPath}logo-icon.svg`,
  },
  DASHBOARD: {
    HEADERMENU: `${iconsPath}sideMenu.svg`,
    HEADERMENUFILL: `${iconsPath}fillhamburger.svg`,
    HEADERLOGO: `${iconsPath}sideHeaderLogo.svg`,
    HEADERSEARCH: `${iconsPath}sideSearch.svg`,
    HEADERUPLOAD: `${iconsPath}sideUploaded.svg`,
    HEADERDISCUSSION: `${iconsPath}sideDiscussion.svg`,
    HEADERMEETING: `${iconsPath}sideMeetings.svg`,
    HEADERNOTIFICATION: `${iconsPath}sideNotification.svg`,
    DASHBOARD: `${iconsPath}Document.svg`,
    MICPURPLE: `${iconsPath}micpurple.svg`,
    MUTEMICPURPLE: `${iconsPath}mutemicpurple.svg`,
    CAMERAPURPLE: `${iconsPath}purplecamera.svg`,
    MUTECAMERAPURPLE: `${iconsPath}purplecameraoff.svg`,
    MEETING: `${iconsPath}sideLive.svg`,
    FORUM: `${iconsPath}sideForum.svg`,
    CONTENT: `${iconsPath}sideContent.svg`,
    CAMERAON: `${iconsPath}cam.svg`,
    OFFCAMERA: `${iconsPath}offcamera.svg`,
    FAV: `${iconsPath}sideFav.svg`,
    MUTEICON: `${iconsPath}muteicon.svg`,
    UNMUTEDICON: `${iconsPath}unmuteicon.svg`,
    MESSAGE: `${iconsPath}sideMessage.svg`,
    PROGRESS: `${iconsPath}sideProgress.svg`,
    SETTING: `${iconsPath}sideSetting.svg`,
    MODALSETTING: `${iconsPath}modalSetting.svg`,
    MODALIMAGE: `${iconsPath}modalImage.png`,
    MODALPROFILE: `${iconsPath}modalProfile.svg`,
    MODALLOGOUT: `${iconsPath}modalLogout.svg`,
    MODALCLOSE: `${iconsPath}modalClose.svg`,
    MODALCONTENT: `${iconsPath}modalContent.svg`,
    VIDEOSTAR: `${iconsPath}videoStar.svg`,
    VIDEODOT: `${iconsPath}videoDot.svg`,
    UPCOMINGREMINDER: `${iconsPath}upcomReminder.svg`,
    UPCOMINGNOTIFICATION: `${iconsPath}upcomNotification.svg`,
    STARFILLED: `${iconsPath}deshStarfilled.svg`,
    DASHBOARDFILLED: `${iconsPath}dashFilled.svg`,
    LIVEMEETINGVIDEO: `${iconsPath}videoIcon.svg`,
    LIVEMEETINGREAD: `${iconsPath}chatRead.svg`,
    LIVEMEETINGSENDCHAT: `${iconsPath}sendChat.svg`,
    LIVEMEETINGPRODUCT: `${iconsPath}product.png`,
    LIVEMEETINGSHOPPINGCARD: `${iconsPath}shoppingCard.svg`,
    ACTIVESIDE2: `${iconsPath}activeSide2.svg`,
    ACTIVESIDE3: `${iconsPath}activeSide3.svg`,
    ACTIVESIDE4: `${iconsPath}activeContentHub.svg`,
    ACTIVESIDE5: `${iconsPath}activeSide5.svg`,
    ACTIVESIDE6: `${iconsPath}activeSide6.svg`,
    ACTIVESIDE7: `${iconsPath}activeSide7.svg`,
    ACTIVESIDE8: `${iconsPath}activeSide8.svg`,
    SUCCESS_MESSAGE_ICON: `${iconsPath}success-message-icon.svg`,
    INFO_MESSAGE_ICON: `${iconsPath}infomessage.svg`,
    ERROR_MESSAGE_ICON: `${iconsPath}error-message-icon.svg`,
    LEAVEICON: `${iconsPath}leaveIcon.svg`,
    MICICON: `${iconsPath}mikeIcon.svg`,
    SEND_ICON: `${iconsPath}send-icon.svg`,
    SEND_ICON_DISABLED: `${iconsPath}send-icon-disabled.svg`,
    DOT: `${iconsPath}dot.svg`,
  },
  LANDING: {
    MENU_OPEN_ICON: `${iconsPath}menu-open-icon.svg`,
    MENU_CLOSE_ICON: `${iconsPath}menu-close-icon.svg`,
    HOME_PROFILE_ICON: `${iconsPath}home-profile-icon.svg`,
    HOME_ACTIVITY_ICON: `${iconsPath}home-activity-icon.svg`,
    HOME_GRAPH_ICON: `${iconsPath}home-graph-icon.svg`,
    HOME_CONTENT_ICON: `${iconsPath}home-content-icon.svg`,
    HOME_NOTIFICATION_ICON: `${iconsPath}home-notification-icon.svg`,
    HOME_CONFERENCING_ICON: `${iconsPath}home-conferencing-icon.svg`,
  },
  AUTH: {
    EMAIL_ICON: `${iconsPath}email-icon.svg`,
  },
  SUGGESTVIDEO: {
    SUBSCRIBE_PLAN: `${iconsPath}bell.svg`,
    NOTIFICATIONBELL: `${iconsPath}notibell.svg`,
    UNSUBSCRIBE_Plan: `${iconsPath}notbell.svg`,
    REPORT: `${iconsPath}report.svg`,
  },
  ONBOARDING: {
    USER_AVATAR: `${iconsPath}onboarding-user-icon.svg`,
    RESTRICTION_CARD_IMAGES: {
      KETO_CARNIVORE: `${iconsPath}restriction-card-keto-icon.svg`,
      VEGETARIAN_VEGAN: `${iconsPath}restriction-card-veg-icon.svg`,
      PALEO: `${iconsPath}restriction-card-paleo-icon.svg`,
      MEDITERRANEAN: `${iconsPath}restriction-card-mediterranean-icon.svg`,
      GLUTEN_FREE: `${iconsPath}restriction-card-gluten-icon.svg`,
      LOW_CARB_SUGAR: `${iconsPath}restriction-card-carb-icon.svg`,
      INTERMITTENT_FASTING: `${iconsPath}restriction-card-fasting-icon.svg`,
      GLP_1_SEMAGLUTIDE: `${iconsPath}restriction-card-semaglutide-icon.svg`,
      LOW_SUGAR: `${iconsPath}restriction-card-sugar-icon.svg`,
      DAIRY_FREE: `${iconsPath}restriction-card-dairy-icon.svg`,
      DOCTOR_PRESCRIBED_DIET: `${iconsPath}restriction-card-diet-icon.svg`,
      CALORIE_COUNTERS: `${iconsPath}restriction-card-counters-icon.svg`,
    },
    COACH_ICON: `${iconsPath}onboarding-coach-icon.svg`,
    MEMBER_ICON: `${iconsPath}onboarding-member-icon.svg`,
  },
  PROFILE: {
    EDIT_ICON: `${iconsPath}profile-edit-icon.svg`,
    LOCATION_ICON: `${iconsPath}profile-location-icon.svg`,
    SUBSCRIBE_ICON: `${iconsPath}profile-subscribe-icon.svg`,
    MESSAGE_ICON: `${iconsPath}profile-message-icon.svg`,
    SHARE_ICON: `${iconsPath}profile-share-icon.svg`,
    REPORT_ICON: `${iconsPath}profile-report-icon.svg`,
    LINKS_ICON: `${iconsPath}profile-links-icon.svg`,
    DROP_EDIT_ICON: `${iconsPath}profile-edit-icon-2.svg`,
    DROP_DELETE_ICON: `${iconsPath}profile-delete-icon.svg`,
  },
  FORUM: {
    SUBSCRIBE_ICON: `${iconsPath}forum-subscribe-icon.svg`,
    UNSUBSCRIBE_ICON: `${iconsPath}forum-unsubscribe-icon.svg`,
    VIDEO_ICON: `${iconsPath}live-video-icon.svg`,
    PRODUCT_LOCK_ICON: `${iconsPath}product-lock-icon.svg`,
  },
  STARLIVEMEETING: {
    VIDEOIMAGE: `${iconsPath}videoimage.svg`,
    STARTMEETINGICON: `${iconsPath}startmeetingicon.svg`,
    UPLOADCONTENTICON: `${iconsPath}uploadcontent.svg`,
  },
  CONTENTHUB: {
    USERIMAGE: `${iconsPath}userimage.svg`,
    EDITSCHEDULETIME: `${iconsPath}editscheduletime.svg`,
    DELETETICON: `${iconsPath}trashicon.svg`,
    REPORTICON: `${iconsPath}reporticon.svg`,
    UNPUBLISHICON: `${iconsPath}unpublishicon.svg`,
    PUBLISHICON: `${iconsPath}publishicon.svg`,
    REPORTDANGER: `${iconsPath}reportdanger.svg`,
    SUBMITREPORT: `${iconsPath}submitreport.svg`,
    MIC: `${iconsPath}mic.svg`,
    CAMERAA: `${iconsPath}cameraa.svg`,
    VIDEOMENU: `${iconsPath}videomenu.svg`,
    PARTICIPATE: `${iconsPath}participate.svg`,
    REQSTJOIN: `${iconsPath}requestjoin.svg`,
    RAISEHAND: `${iconsPath}raisehand.svg`,
    DOTICON: `${iconsPath}doticon.svg`,
    LEAVEICON: `${iconsPath}leaveIcon.svg`,
    BELLICON: `${iconsPath}bellicon.svg`,
    THUMBLIKE: `${iconsPath}thumblike.svg`,
    THUMBUNLIKE: `${iconsPath}unlike.svg`,
    FAVORITE: `${iconsPath}favoriteicon.svg`,
    SHARE: `${iconsPath}Shareicon.svg`,
    REPORT: `${iconsPath}reporticonimg.svg`,
    GOLIVE: `${iconsPath}golive.svg`,
    STARTMEETING: `${iconsPath}startmeeting.svg`,
    PURPLEDOT: `${iconsPath}Purpledot.svg`,
    NOTALLOW: `${iconsPath}notallow.svg`,
    DISABLECHAT: `${iconsPath}disablechat.svg`,
    LEAVEMEETING: `${iconsPath}leavemeeting.svg`,
    SUBSCRIBENOTIFICATION: `${iconsPath}subnotification.svg`,
    UPLOADCONTENTICON: `${iconsPath}uploadcontenticon.svg`,
    UPLOADCONTENTWHITE: `${iconsPath}uploadcontentwhite.svg`,
    REDLEAVEICON: `${iconsPath}redleaveicon.svg`,
  },
};

export default ICON;
