export const ROUTES = {
  ROOT: "/",
  ABOUT_US: "/about-us",
  CONTACT_US: "/contact-us",
  BLOGS: "/blogs",
  BLOG_DETAILS: "/blogs/blog",
  FAQ: "/faq",
  PRIVACY_POLICY: "/privacy-policy",
  TERMS_OF_SERVICE: "/terms-of-service",
  LOGIN: "/login",
  SIGNUP: "/signup",
  ENABLE_2FA: "/enable-2fa",
  OTP_VERIFICATION: "/verification",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  ONBOARDING: "/onboarding",
  MEMBER: "/member",
  COACH: "/coach",
  DASHBOARD: "/dashboard",
  DASHBOARD_LIVE_MEETINGS: "/dashboard/live-meetings",
  DASHBOARD_LIVE_MEETINGS_VIEWER: "/dashboard/live-meetings/viewer/:id",
  DASHBOARD_RECORDED_CONTENT_VIEWER: "/dashboard/recorded-content/viewer/:id",
  DASHBOARD_UPLOADED_CONTENT_VIEWER: "/dashboard/uploaded-content/viewer/:id",
  DASHBOARD_UPLOAD_CONTENT: "/dashboard/upload-content",
  DASHBOARD_FAVORITES: "/dashboard/favorites",
  DASHBOARD_MESSAGES: "/dashboard/messages",
  DASHBOARD_MESSAGES_ID: "/dashboard/messages?id=",
  DASHBOARD_FORUM: "/dashboard/forum",
  DASHBOARD_FORUM_POST_DETAILS: "/dashboard/forum/post-details",
  DASHBOARD_FORUM_NEW_POST: "/dashboard/forum/new-post",
  DASHBOARD_PROGRESS: "/dashboard/progress",
  DASHBOARD_SETTINGS: "/dashboard/settings",
  DASHBOARD_SETTINGS_PERSONAL_INFO: "/dashboard/settings/personal-info",
  DASHBOARD_SETTINGS_SECURITY: "/dashboard/settings/security",
  DASHBOARD_SETTINGS_NOTIFICATIONS: "/dashboard/settings/notifications",
  DASHBOARD_SETTINGS_SUBSCRIPTION: "/dashboard/settings/subscription",
  DASHBOARD_SETTINGS_TERMS_CONDITIONS: "/dashboard/settings/terms-conditions",
  DASHBOARD_SETTINGS_PRIVACY_POLICY: "/dashboard/settings/privacy-policy",
  DASHBOARD_PROFILE: "/dashboard/profile",
  DASHBOARD_START_LIVE_MEETING: "/dashboard/start-live-meeting",
  DASHBOARD_STAR_LIVE_MEETING_LIVE: "/dashboard/start-live-meeting/viewer/:id",
  DASHBOARD_CONTENTHUB: "/dashboard/content-hub",
};

export default ROUTES;
